services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Mpay24Seamless:
        arguments:
            $options: []
        tags:
            - { name: pimcore_ecommerce.payment.provider, key: 'mpay24' }

    Pimcore\Bundle\EcommerceFrameworkBundle\Mpay24Seamless\Installer:
        public: true
